"""
setup_model.py
--------------
Downloads a ready-made AI-text detector from HuggingFace and saves it
locally into ./model/distilbert_model so the rest of the AITAG project
works without any changes.

Model: Hello-SimpleAI/chatgpt-detector-roberta
  - Fine-tuned RoBERTa-base on Human vs ChatGPT text
  - ~500 MB download
  - Labels: 0 = Human, 1 = ChatGPT (AI)
  - Works on CPU, fits in 8 GB RAM easily

Run:
    python setup_model.py

Requires:
    pip install transformers torch
"""

import os
import sys
from pathlib import Path

# ── Check dependencies ────────────────────────────────────────────────────
try:
    from transformers import AutoTokenizer, AutoModelForSequenceClassification
    import torch
except ImportError:
    print("ERROR: transformers or torch not installed.")
    print("Run:  pip install transformers torch")
    sys.exit(1)

# ── Config ────────────────────────────────────────────────────────────────

HF_MODEL_ID  = "Hello-SimpleAI/chatgpt-detector-roberta"
SAVE_PATH    = Path("./model/distilbert_model")   # keep same path so config.py needs no changes
ENV_FILE     = Path(".env")

# ── Download ──────────────────────────────────────────────────────────────

print(f"\nDownloading model: {HF_MODEL_ID}")
print(f"Saving to        : {SAVE_PATH.resolve()}")
print(f"Estimated size   : ~500 MB\n")
print("This may take a few minutes on first run...\n")

SAVE_PATH.mkdir(parents=True, exist_ok=True)

tokenizer = AutoTokenizer.from_pretrained(HF_MODEL_ID)
model     = AutoModelForSequenceClassification.from_pretrained(HF_MODEL_ID)

tokenizer.save_pretrained(str(SAVE_PATH))
model.save_pretrained(str(SAVE_PATH))

print(f"\n✓ Model saved to {SAVE_PATH.resolve()}")

# ── Patch .env ────────────────────────────────────────────────────────────

env_content = f"""# AITAG environment config — auto-generated by setup_model.py

# Path to model (RoBERTa-based ChatGPT detector)
AITAG_MODEL_PATH=./model/distilbert_model

# Confidence below which result is marked Uncertain
AITAG_CONFIDENCE_THRESHOLD=0.70

# auto = use CUDA if available, else CPU
AITAG_DEVICE=auto

# Hex chars of SHA-256 stored in watermark (8 = 32-bit)
AITAG_HASH_LENGTH=8
"""

ENV_FILE.write_text(env_content, encoding="utf-8")
print(f"✓ .env written")

# ── Patch config.py to use AutoModel instead of DistilBert classes ────────

CONFIG_PATCH = Path("config.py")
if CONFIG_PATCH.exists():
    print(f"✓ config.py already exists — no changes needed")

CLASSIFIER_PATH = Path("core/classifier.py")
if CLASSIFIER_PATH.exists():
    src = CLASSIFIER_PATH.read_text(encoding="utf-8")
    if "DistilBertTokenizer" in src:
        src = src.replace(
            "from transformers import DistilBertTokenizer, DistilBertForSequenceClassification",
            "from transformers import AutoTokenizer, AutoModelForSequenceClassification"
        )
        src = src.replace(
            "tokenizer = DistilBertTokenizer.from_pretrained(str(path), local_files_only=True)",
            "tokenizer = AutoTokenizer.from_pretrained(str(path), local_files_only=True)"
        )
        src = src.replace(
            "model = DistilBertForSequenceClassification.from_pretrained(\n        str(path), num_labels=2, local_files_only=True\n    )",
            "model = AutoModelForSequenceClassification.from_pretrained(str(path), local_files_only=True)"
        )
        CLASSIFIER_PATH.write_text(src, encoding="utf-8")
        print(f"✓ core/classifier.py patched to use AutoTokenizer / AutoModelForSequenceClassification")
    else:
        print(f"✓ core/classifier.py already uses Auto classes — no patch needed")

# ── Quick sanity test ─────────────────────────────────────────────────────

print("\nRunning quick sanity check...")

tokenizer_check = AutoTokenizer.from_pretrained(str(SAVE_PATH), local_files_only=True)
model_check     = AutoModelForSequenceClassification.from_pretrained(str(SAVE_PATH), local_files_only=True)
model_check.eval()

test_texts = [
    ("As the sun dipped below the horizon, I sat on the porch thinking about nothing in particular.",
     "Human"),
    ("Large language models are neural networks trained on vast corpora of text data using self-supervised learning objectives.",
     "AI"),
]

print()
for text, expected in test_texts:
    inputs = tokenizer_check(text, return_tensors="pt", truncation=True, max_length=128)
    with torch.no_grad():
        probs = model_check(**inputs).logits.softmax(dim=1)[0]
    idx   = probs.argmax().item()
    label = ["Human", "ChatGPT"][idx]
    conf  = probs.max().item() * 100
    mark  = "✓" if label.startswith(expected) or expected in label else "?"
    print(f"  {mark}  [{label:10s} {conf:5.1f}%]  {text[:65]}...")

print("""
══════════════════════════════════════════════════════
  Setup complete. You can now run:

    python cli.py your_file.txt --tag --verify

  or start the API:

    uvicorn api.server:app --reload --port 8000
══════════════════════════════════════════════════════
""")
